; file:GateXpr_lvo.i
;
; generated by FixFD v1.0
;
; Bias = 30
;
_LVOTransferSetup	equ -30
_LVOReceiveFile	equ -36
_LVOSendFile	equ -42
_LVOGetOptions	equ -48
_LVOSetOptions	equ -54
_LVOTransferSetupShared	equ -60
_LVOInstallTransferNote	equ -66
_LVOSendMultipleFiles	equ -72
